basePath: /
consumes:
- application/json
definitions:
  Decimal:
    description: number = value * 10 ^ exp
    title: Decimal represents a fixed-point decimal. It is immutable.
    type: object
    x-go-package: github.com/shopspring/decimal
  LimitOrder:
    properties:
      order_id:
        description: |-
          order id

          in: query
        example: order-1
        type: string
        x-go-name: OrderId
      price:
        $ref: '#/definitions/Decimal'
      quantity:
        $ref: '#/definitions/Decimal'
      side:
        description: |-
          enum 0 for sell and 1 for buy

          in: query
        example: 0
        format: int32
        type: integer
        x-go-name: Side
    type: object
    x-go-package: spotob/src/models
  MarketOrderRequest:
    description: |-
      swagger: parameters
      Market order request
    properties:
      quantity:
        $ref: '#/definitions/Decimal'
      side:
        description: |-
          swagger: model
          enum 0 for sell and 1 for buy
        format: int32
        type: integer
        x-go-name: Side
    required:
    - side
    - quantity
    type: object
    x-go-package: spotob/src/models
info:
  description: Documentation for Spot OrderBook API
  title: Spot OrderBook API
  version: 1.0.0
paths:
  /cancelOrder/{id}:
    get:
      operationId: cancelOrder
      parameters:
      - description: id of the order to cancel
        in: path
        name: order id
        required: true
        schema:
          description: id of the order to cancel
          format: int
          type: integer
        type: integer
      responses:
        "200":
          $ref: '#/responses/order'
        "401":
          $ref: '#/responses/ErrorResponse'
      tags:
      - order
  /depth:
    get:
      operationId: depth
      responses:
        "200":
          $ref: '#/responses/OrderBookDepth'
        "401":
          $ref: '#/responses/ErrorResponse'
  /processLimitOrder:
    post:
      description: Create a new limit order
      operationId: processLimitOrder
      parameters:
      - in: body
        name: LimitOrderRequest
        required: true
        schema:
          $ref: '#/definitions/LimitOrderRequest'
          type: object
        type: object
      responses:
        "200":
          description: ResLimitOrder
          schema:
            $ref: '#/definitions/ResLimitOrder'
        "401":
          $ref: '#/responses/ErrorResponse'
        "404":
          $ref: '#/responses/ErrorResponse'
        "500":
          $ref: '#/responses/ErrorResponse'
  /processMarketOrder:
    post:
      description: Create a new market order for processing
      operationId: processMarketOrder
      parameters:
      - in: body
        name: market order
        required: true
        schema:
          $ref: '#/definitions/MarketOrderRequest'
          format: object
          type: object
        type: object
      responses:
        "200":
          $ref: '#/responses/ResMarketOrder'
        "401":
          $ref: '#/responses/ErrorResponse'
produces:
- application/json
responses:
  ErrorResponse:
    description: An Error response
    headers:
      code:
        description: |-
          The error message
          name code
        format: int64
        type: integer
      errors:
        description: errors
    schema:
      additionalProperties:
        type: string
      type: object
schemes:
- http
swagger: "2.0"
